#!/bin/bash

xfst -f MonishGuesserAnalyzer.xfst.script
cat MonishGuesserAnalyzer | ../xfst-att-to-hfst-att.sh \
  > MonishGuesserAnalyzer.xfst.att

hfst-txt2fst -f openfst-tropical MonishGuesserAnalyzer.xfst.att > \
  MonishGuesserAnalyzer.xfst.hfst

for i in openfst-tropical; do
# for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" MonishGuesserAnalyzer.hfst.script
  echo "Testing" $i "..."
  sh MonishGuesserAnalyzer.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" MonishGuesserAnalyzer.hfst.script
  hfst-fst2fst -f openfst-tropical MonishGuesserAnalyzer.hfst.hfst > TMP
  hfst-compare -q TMP MonishGuesserAnalyzer.xfst.hfst && echo "TEST PASSED";
done
