#!/bin/bash
TOOLDIR=../../tools/src

xfst -f MonishAnalysis.xfst.script
cat MonishAnalysis | ../xfst-att-to-$TOOLDIR/hfst-att.sh \
  > MonishAnalysis.xfst.att

$TOOLDIR/hfst-txt2fst -f openfst-tropical MonishAnalysis.xfst.att > \
  MonishAnalysis.xfst.hfst

for i in openfst-tropical; do
# for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" MonishAnalysis.hfst.script
  echo "Testing" $i "..."
  sh MonishAnalysis.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" MonishAnalysis.hfst.script
  $TOOLDIR/hfst-fst2fst -f openfst-tropical MonishAnalysis.hfst.hfst > TMP
  $TOOLDIR/hfst-compare -q TMP MonishAnalysis.xfst.hfst && echo "TEST PASSED";
done
