#!/bin/bash

NUMBER_OF_TESTS=`ls $srcdir | egrep "test[0-9][0-9]*$" | wc -l`

echo "There are $NUMBER_OF_TESTS substests for hfst-twolc."

for f in $(ls $srcdir | egrep "test[0-9][0-9]*$")
do
	cat $f | ../src/hfst-twolc-loc -R -s | hfst-fst2txt | hfst-txt2fst -e"@_EPSILON_SYMBOL_@" > temp.twolc.hfst
	cat $f.txt_fst | hfst-txt2fst -e"@_EPSILON_SYMBOL_@" > temp.hfst
	if ! hfst-compare -q -1 temp.hfst -2 temp.twolc.hfst &> /dev/null
	then
		echo "hfst-twolc sub$f failed."
		echo
		echo "Grammar:"
		echo
		cat $f
		echo
		echo "Should be:"
		echo
		hfst-fst2txt temp.hfst
		echo
		echo "Is:"
		echo
		hfst-fst2txt temp.twolc.hfst
		echo
		rm temp.hfst temp.twolc.hfst
		exit 1
	else
	    echo "hfst-twolc sub$f passed."
	fi
done

rm temp.hfst temp.twolc.hfst

