#!/bin/bash

# xfst -f YaleShooting.xfst.script
# cat YaleShooting | ../xfst-att-to-hfst-att.sh > YaleShooting.xfst.att

hfst-txt2fst -f openfst-tropical YaleShooting.xfst.att > \
  YaleShooting.xfst.hfst

for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" YaleShooting.hfst.script
  echo "Testing" $i "..."
  sh YaleShooting.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" YaleShooting.hfst.script
  hfst-fst2fst -f openfst-tropical YaleShooting.hfst.hfst > TMP
  hfst-compare -q TMP YaleShooting.xfst.hfst && echo "TEST PASSED";
done
