#!/bin/bash
TOOLDIR=../../tools/src

# xfst -f Lingala.xfst.script
# cat Lingala | ../xfst-att-to-$TOOLDIR/hfst-att.sh > Lingala.xfst.att

$TOOLDIR/hfst-txt2fst -f openfst-tropical Lingala.xfst.att > \
  Lingala.xfst.hfst

for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" Lingala.hfst.script
  echo "Testing" $i "..."
  sh Lingala.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" Lingala.hfst.script
  $TOOLDIR/hfst-fst2fst -f openfst-tropical Lingala.hfst.hfst > TMP
  $TOOLDIR/hfst-compare -q TMP Lingala.xfst.hfst && echo "TEST PASSED";
done
