#!/bin/bash
TOOLDIR=../../../../tools/src

for i in sfst openfst-tropical foma; do
  echo "Testing" $i "..."
  sh FinnishProsody.hfst.script $i $TOOLDIR

# Print the lexicon with prosody indicated.
rm -f result
cat FinnProsody | $TOOLDIR/hfst-project -p output | $TOOLDIR/hfst-fst2strings | sort > result


    rm -f expected_result ;
    sort expected_result.strings > expected_result
    diff expected_result result && echo "TEST PASSED";
done





