#!/bin/bash

# xfst -f PlusOrMinus.xfst.script
# for i in One Two Three Four Five Six Seven Eight Nine; do \
#   cat "PlusMinus"$i >> TMP;
#   echo "--" >> TMP;
# done
# cat PlusMinusTen >> TMP;
# cat TMP | ./xfst-att-to-hfst-att.sh > PlusOrMinus.xfst.hfst

hfst-txt2fst -f openfst-tropical PlusOrMinus.xfst.att > \
  PlusOrMinus.xfst.hfst

for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" PlusOrMinus.hfst.script
  echo "Testing" $i "..."
  sh PlusOrMinus.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" PlusOrMinus.hfst.script
  hfst-fst2fst -f openfst-tropical PlusOrMinus.hfst.hfst > TMP
  hfst-compare -q TMP PlusOrMinus.xfst.hfst && echo "TEST PASSED";
done
