echo "yellow Norwegian water Dunhill cats |"\
     "blue Dane tea Blend horses |"\
     "red Englishman milk PallMall birds |"\
     "green German coffee Prince fish |"\
     "white Swede bier BlueMaster dogs " > expected_result

for i in sfst openfst-tropical; do # foma
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" EinsteinsPuzzle.hfst.script
  echo "Testing" $i "..."
  bash EinsteinsPuzzle.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" EinsteinsPuzzle.hfst.script
  diff -q result expected_result && echo "TEST PASSED"; 
done
