#!/bin/bash
TOOLDIR=../../tools/src

echo '([MF%+:g 0:e])' | $TOOLDIR/hfst-regexp2fst -f $1 > NounPrefix

echo "bird
hund
kat
elefant" | $TOOLDIR/hfst-strings2fst -j -f $1 > NounRoots

echo "bon
long
jun
alt
grav" | $TOOLDIR/hfst-strings2fst -j -f $1 > AdjRoots

echo "don
est
pens
dir
fal" | $TOOLDIR/hfst-strings2fst -j -f $1 > VerbRoots

echo '([Op%+:m 0:a 0:l] | [Neg%+:n 0:e])' | $TOOLDIR/hfst-regexp2fst -f $1 \
     > VerbPrefixes

echo '[%+Verb:0]' | $TOOLDIR/hfst-regexp2fst -f $1 > Verb

echo '([%+Cont:a 0:d])' | $TOOLDIR/hfst-regexp2fst -f $1 > Aspect

echo '[%+Inf:i] | [%+Pres:a 0:s] | [%+Past:i 0:s] | [%+Fut:o 0:s] | ' \
     '[%+Cond:u 0:s] | [%+Subj:u]' | $TOOLDIR/hfst-regexp2fst -f $1 > Vend


echo '%+Noun:0' | $TOOLDIR/hfst-regexp2fst -f $1 > Nmf

echo '%+NSuff:o' | $TOOLDIR/hfst-regexp2fst -f $1 > Nend

echo '%+ASuff:a' | $TOOLDIR/hfst-regexp2fst -f $1 > Adjend

echo '[[%+Fem:i 0:n] | [%+Dim:e 0:t] | [%+Aug:e 0:g]]* [@"Nend" | @"Adjend"]' \
     | $TOOLDIR/hfst-regexp2fst -f $1 > AugDimFem 

echo '([Op%+:m 0:a 0:l] | [Neg%+:n 0:e])' | $TOOLDIR/hfst-regexp2fst -f $1 \
     > AdjPrefixes

echo '[[%+Aug:e 0:g] | [%+Dim:e 0:t]]* [[[%+Nize:e 0:c] @"Nend"]|[@"Adjend"]]' \
     | $TOOLDIR/hfst-regexp2fst -f $1 > AugDimNize

echo '%+Adj:0' | $TOOLDIR/hfst-regexp2fst -f $1 > Adj

echo '%+Pl:j | %+Sg:0' | $TOOLDIR/hfst-regexp2fst -f $1 > Number

echo '(%+Acc:n)' | $TOOLDIR/hfst-regexp2fst -f $1 > Case
	

$TOOLDIR/hfst-concatenate NounPrefix NounRoots | $TOOLDIR/hfst-concatenate -2 Nmf | \
  $TOOLDIR/hfst-concatenate -2 AugDimFem  > NounStem

$TOOLDIR/hfst-concatenate AdjPrefixes AdjRoots | $TOOLDIR/hfst-concatenate -2 Adj | \
  $TOOLDIR/hfst-concatenate -2 AugDimNize > AdjectiveStem

$TOOLDIR/hfst-disjunct NounStem AdjectiveStem > NounAdjStems
$TOOLDIR/hfst-concatenate Number Case | $TOOLDIR/hfst-concatenate -1 NounAdjStems > NounAdjs

$TOOLDIR/hfst-concatenate VerbPrefixes VerbRoots | $TOOLDIR/hfst-concatenate -2 Verb | \
$TOOLDIR/hfst-concatenate -2 Aspect | $TOOLDIR/hfst-concatenate -2 Vend > Verbs

$TOOLDIR/hfst-disjunct NounAdjs Verbs | $TOOLDIR/hfst-minimize \
  > EsperantoNounsAdjectivesAndVerbs

rm -f NounStem NounAdjStems Aspect Verbs NounAdjs VerbRoots AdjRoots
rm -f Adjend Number AugDimNize NounPrefix AugDimFem AdjPrefixes
rm -f VerbPrefixes NounRoots Case Nmf Nend AdjectiveStem Vend Verb Adj
