#!/bin/bash
TOOLDIR=../../tools/src

echo '[( [m a l] | [n e] )]' | $TOOLDIR/hfst-regexp2fst -f $1 -j > AdjPrefix

echo "bon
long
jun
alt
grav" | $TOOLDIR/hfst-strings2fst -f $1 -j > Adjectives

echo '[[e g] | [e t]]*' | $TOOLDIR/hfst-regexp2fst -f $1 -j > Adj

echo '[a]' | $TOOLDIR/hfst-regexp2fst -f $1 -j > AdjEnd

echo '[(j)]' | $TOOLDIR/hfst-regexp2fst -f $1 -j > Number

echo '[(n)]' | $TOOLDIR/hfst-regexp2fst -f $1 -j > Case

echo '[0]' | $TOOLDIR/hfst-regexp2fst -f $1 > Result
for i in AdjPrefix Adjectives Adj AdjEnd Number Case;
do
  $TOOLDIR/hfst-concatenate Result $i > TMP;
  mv TMP Result;
done

$TOOLDIR/hfst-minimize Result > EsperantoAdjectives
