#!/bin/bash

# hfst-xfst -f EnglishNumerals.xfst.script
hfst-txt2fst -f openfst-tropical EnglishNumerals.xfst.att > \
  EnglishNumerals.xfst.hfst

for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" EnglishNumerals.hfst.script
  echo "Testing" $i "..."
  sh EnglishNumerals.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" EnglishNumerals.hfst.script
  hfst-fst2fst -f openfst-tropical EnglishNumerals.hfst.hfst > TMP
  hfst-compare -q TMP EnglishNumerals.xfst.hfst && echo "TEST PASSED";
done
