# hfst-xfst -f DateParser.xfst.script
hfst-txt2fst -f openfst-tropical DateParser.xfst.att > \
  DateParser.xfst.hfst

for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" DateParser.hfst.script
  echo "Testing" $i "..."
  sh DateParser.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" DateParser.hfst.script
  hfst-fst2fst -f openfst-tropical DateParser.hfst.hfst > TMP
  hfst-compare -q TMP DateParser.xfst.hfst && echo "TEST PASSED";
done
