#!/bin/bash
TOOLDIR=../../tools/src

# xfst -f BetterColaMachine.xfst.script
# cat BetterColaMachine | ../xfst-att-to-$TOOLDIR/hfst-att.sh 
#   > BetterColaMachine.xfst.att

$TOOLDIR/hfst-txt2fst -f openfst-tropical BetterColaMachine.xfst.att > \
  BetterColaMachine.xfst.hfst

for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" BetterColaMachine.hfst.script
  echo "Testing" $i "..."
  sh BetterColaMachine.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" BetterColaMachine.hfst.script
  $TOOLDIR/hfst-fst2fst -f openfst-tropical BetterColaMachine.hfst.hfst > TMP
  $TOOLDIR/hfst-compare -q TMP BetterColaMachine.xfst.hfst && echo "TEST PASSED";
done
