#!/bin/bash
TOOLDIR=../../tools/src

echo "bird
hund
kat
elefant" | $TOOLDIR/hfst-strings2fst -j -f $1 > NounRoots

echo "bon
long
jun
alt
grav" | $TOOLDIR/hfst-strings2fst -j -f $1 > AdjRoots

echo '[(g e)]' | $TOOLDIR/hfst-regexp2fst -f $1 > NounPrefix

echo '[ ([m a l] | [n e]) ]' | $TOOLDIR/hfst-regexp2fst -f $1 > AdjPrefixes

echo '[o]' | $TOOLDIR/hfst-regexp2fst -f $1 -j > Nend

echo '[a]' | $TOOLDIR/hfst-regexp2fst -f $1 -j > Adjend

echo '[(j)]' | $TOOLDIR/hfst-regexp2fst -f $1 -j > Number

echo '[(n)]' | $TOOLDIR/hfst-regexp2fst -f $1 -j > Case

echo '[ ([i n] | [e t] | [e g])* [@"Nend" | @"Adjend"] ]' | \
     $TOOLDIR/hfst-regexp2fst -f $1 > Nmf

echo '([e g] | [e t])* [@"Adjend" | [e c @"Nend"]]' | \
     $TOOLDIR/hfst-regexp2fst -f $1 > Adj

$TOOLDIR/hfst-concatenate NounPrefix NounRoots | $TOOLDIR/hfst-concatenate -2 Nmf > NounStem
$TOOLDIR/hfst-concatenate AdjPrefixes AdjRoots | $TOOLDIR/hfst-concatenate -2 Adj > AdjectiveStem
$TOOLDIR/hfst-disjunct NounStem AdjectiveStem > Stems
$TOOLDIR/hfst-concatenate Number Case | $TOOLDIR/hfst-concatenate -1 Stems > Result

$TOOLDIR/hfst-minimize Result > EsperantoNounsAndAdjectives.hfst.hfst
