#!/bin/bash

echo '([MF%+:g 0:e])' | hfst-regexp2fst -f $1 > NounPrefix

echo "bird
hund
kat
elefant" | hfst-strings2fst -j -f $1 > NounRoots

echo "bon
long
jun
alt
grav" | hfst-strings2fst -j -f $1 > AdjRoots

echo "don
est
pens
dir
fal" | hfst-strings2fst -j -f $1 > VerbRoots

echo '([Op%+:m 0:a 0:l] | [Neg%+:n 0:e])' | hfst-regexp2fst -f $1 \
     > VerbPrefixes

echo '[%+Verb:0]' | hfst-regexp2fst -f $1 > Verb

echo '([%+Cont:a 0:d])' | hfst-regexp2fst -f $1 > Aspect

echo '[%+Inf:i] | [%+Pres:a 0:s] | [%+Past:i 0:s] | [%+Fut:o 0:s] | ' \
     '[%+Cond:u 0:s] | [%+Subj:u]' | hfst-regexp2fst -f $1 > Vend


echo '%+Noun:0' | hfst-regexp2fst -f $1 > Nmf

echo '%+NSuff:o' | hfst-regexp2fst -f $1 > Nend

echo '%+ASuff:a' | hfst-regexp2fst -f $1 > Adjend

echo '[[%+Fem:i 0:n] | [%+Dim:e 0:t] | [%+Aug:e 0:g]]* [@"Nend" | @"Adjend"]' \
     | hfst-regexp2fst -f $1 > AugDimFem 

echo '([Op%+:m 0:a 0:l] | [Neg%+:n 0:e])' | hfst-regexp2fst -f $1 \
     > AdjPrefixes

echo '[[%+Aug:e 0:g] | [%+Dim:e 0:t]]* [[[%+Nize:e 0:c] @"Nend"]|[@"Adjend"]]' \
     | hfst-regexp2fst -f $1 > AugDimNize

echo '%+Adj:0' | hfst-regexp2fst -f $1 > Adj

echo '%+Pl:j | %+Sg:0' | hfst-regexp2fst -f $1 > Number

echo '(%+Acc:n)' | hfst-regexp2fst -f $1 > Case
	

hfst-concatenate NounPrefix NounRoots | hfst-concatenate -2 Nmf | \
  hfst-concatenate -2 AugDimFem  > NounStem

hfst-concatenate AdjPrefixes AdjRoots | hfst-concatenate -2 Adj | \
  hfst-concatenate -2 AugDimNize > AdjectiveStem

hfst-disjunct NounStem AdjectiveStem > NounAdjStems
hfst-concatenate Number Case | hfst-concatenate -1 NounAdjStems > NounAdjs

hfst-concatenate VerbPrefixes VerbRoots | hfst-concatenate -2 Verb | \
hfst-concatenate -2 Aspect | hfst-concatenate -2 Vend > Verbs

hfst-disjunct NounAdjs Verbs | hfst-minimize \
  > EsperantoNounsAdjectivesAndVerbs.hfst.hfst
