#!/bin/bash

echo 'bird
hund
kat
elefant' | hfst-strings2fst -j -f $1 > Nouns

echo '[ [i n] | [e t] | [e g] ]*'| hfst-regexp2fst -f $1 > Nmf

echo '[o]' | hfst-regexp2fst -f $1 > Nend

echo '[(j)]' | hfst-regexp2fst -f $1 > Number

echo '[(n)]' | hfst-regexp2fst -f $1 > Case

echo '[0]' | hfst-regexp2fst -f $1 > Result
for i in Nouns Nmf Nend Number Case;
do
  hfst-concatenate Result $i > TMP;
  mv TMP Result;
done

hfst-minimize Result > EsperantoNouns.hfst.hfst
