#!/bin/bash

echo '[( [m a l] | [n e] )]' | hfst-regexp2fst -f $1 -j > AdjPrefix

echo "bon
long
jun
alt
grav" | hfst-strings2fst -f $1 -j > Adjectives

echo '[[e g] | [e t]]*' | hfst-regexp2fst -f $1 -j > Adj

echo '[a]' | hfst-regexp2fst -f $1 -j > AdjEnd

echo '[(j)]' | hfst-regexp2fst -f $1 -j > Number

echo '[(n)]' | hfst-regexp2fst -f $1 -j > Case

echo '[0]' | hfst-regexp2fst -f $1 > Result
for i in AdjPrefix Adjectives Adj AdjEnd Number Case;
do
  hfst-concatenate Result $i > TMP;
  mv TMP Result;
done

hfst-minimize Result > EsperantoAdjectives.hfst.hfst
