#!/bin/bash
TOOLDIR=../../tools/src

echo 'bird
hund
kat
elefant' | $TOOLDIR/hfst-strings2fst -j -f $1 > Nouns

echo '[ [i n] | [e t] | [e g] ]*'| $TOOLDIR/hfst-regexp2fst -f $1 > Nmf

echo '[o]' | $TOOLDIR/hfst-regexp2fst -f $1 > Nend

echo '[(j)]' | $TOOLDIR/hfst-regexp2fst -f $1 > Number

echo '[(n)]' | $TOOLDIR/hfst-regexp2fst -f $1 > Case

echo '[0]' | $TOOLDIR/hfst-regexp2fst -f $1 > Result
for i in Nouns Nmf Nend Number Case;
do
  $TOOLDIR/hfst-concatenate Result $i > TMP;
  mv TMP Result;
done

$TOOLDIR/hfst-minimize Result > EsperantoNouns.hfst.hfst
