#!/bin/bash

for i in EsperantoAdjectives \
      	 EsperantoNounsAndAdjectives \
	 EsperantoNounsAndAdjectivesWithTags \
	 EsperantoNouns;
do
  # compile with xfst
  echo 'read lexc < "'$i'.lexc"; write att "'$i'" FOO BAR;' | xfst \
      2>1 > /dev/null;
  cat $i | ../xfst-att-to-hfst-att.sh > $i.xfst.att;
  cat $i.xfst.att | hfst-txt2fst -f openfst-tropical > $i.xfst.hfst;

  # compile with different HFST backends
  for j in sfst openfst-tropical foma;
  do
    sed -i '1s/TRANSDUCER_FORMAT/'$j'/;' $i.hfst.script;
    bash $i.hfst.script;
    sed -i '1s/'$j'/TRANSDUCER_FORMAT/;' $i.hfst.script;
    # test for equivalence
    hfst-fst2fst -f openfst-tropical $i.hfst.hfst > TMP;
    if ! hfst-compare -q TMP $i.xfst.hfst; then
      exit 1;
    fi;
  done;

done
