# hfst-xfst -f NumbersToNumerals.xfst.script
hfst-txt2fst -f openfst-tropical NumbersToNumerals.xfst.att > \
  NumbersToNumerals.xfst.hfst
hfst-project -p input NumbersToNumerals.xfst.hfst > expected_input
hfst-project -p output NumbersToNumerals.xfst.hfst > expected_output

for i in sfst openfst-tropical foma; do
  sed -i "1s/TRANSDUCER_FORMAT/"$i"/;" NumbersToNumerals.hfst.script
  echo "Testing" $i "..."
  sh NumbersToNumerals.hfst.script
  sed -i "1s/"$i"/TRANSDUCER_FORMAT/;" NumbersToNumerals.hfst.script
  hfst-project -p input NumbersToNumerals.hfst.hfst \
  | hfst-fst2fst -f openfst-tropical > result_input
  hfst-project -p output NumbersToNumerals.hfst.hfst \
  | hfst-fst2fst -f openfst-tropical > result_output
  hfst-compare -q expected_input result_input && \
  hfst-compare -q expected_input result_input && \
  echo "TEST PASSED";
done
