hfst-xfst -f NumbersToNumerals.xfst.script;
sh NumbersToNumerals.hfst.script;

hfst-project -p input NumbersToNumerals.xfst.hfst > xfst.input;
hfst-project -p output NumbersToNumerals.xfst.hfst > xfst.output;

hfst-project -p input NumbersToNumerals.hfst.hfst > hfst.input;
hfst-project -p output NumbersToNumerals.hfst.hfst > hfst.output;

hfst-compare -v xfst.input hfst.input;
hfst-compare -v xfst.output hfst.output;
